feed_categories:
  press_releases:
    - title: "Complexity Digest"
      url: "https://comdig.unam.mx/feed/"
    - title: "Phys.org"
      url: "https://phys.org/rss-feed/"
    - title: "astrobiology.com"
      url: "https://astrobiology.com/rss"
    - title: "ScienceDaily"
      url: "https://www.sciencedaily.com/rss/all.xml"
  
  preprints:
    - title: "biorxiv"
      url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=all"
    - title: "medrxiv"
      url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=all"
    - title: "EarthArXiv"
      url: "https://eartharxiv.org/rss/preprints/"
    - title: "arXiv.org/astro-ph"
      url: "https://rss.arxiv.org/rss/astro-ph"
    - title: "arXiv.org/cond-mat"
      url: "https://rss.arxiv.org/rss/cond-mat"
    - title: "arXiv.org/cs"
      url: "https://rss.arxiv.org/rss/cs"
    - title: "arXiv.org/econ"
      url: "https://rss.arxiv.org/rss/econ"
    - title: "arXiv.org/eess"
      url: "https://rss.arxiv.org/rss/eess"
    - title: "arXiv.org/gr-qc"
      url: "https://rss.arxiv.org/rss/gr-qc"
    - title: "arXiv.org/hep-ex"
      url: "https://rss.arxiv.org/rss/hep-ex"
    - title: "arXiv.org/hep-lat"
      url: "https://rss.arxiv.org/rss/hep-lat"
    - title: "arXiv.org/hep-ph"
      url: "https://rss.arxiv.org/rss/hep-ph"
    - title: "arXiv.org/hep-th"
      url: "https://rss.arxiv.org/rss/hep-th"
    - title: "arXiv.org/math"
      url: "https://rss.arxiv.org/rss/math"
    - title: "arXiv.org/math-ph"
      url: "https://rss.arxiv.org/rss/math-ph"
    - title: "arXiv.org/nlin"
      url: "https://rss.arxiv.org/rss/nlin"
    - title: "arXiv.org/nucl-ex"
      url: "https://rss.arxiv.org/rss/nucl-ex"
    - title: "arXiv.org/nucl-th"
      url: "https://rss.arxiv.org/rss/nucl-th"
    - title: "arXiv.org/physics"
      url: "https://rss.arxiv.org/rss/physics"
    - title: "arXiv.org/q-bio"
      url: "https://rss.arxiv.org/rss/q-bio"
    - title: "arXiv.org/q-fin"
      url: "https://rss.arxiv.org/rss/q-fin"
    - title: "arXiv.org/quant-ph"
      url: "https://rss.arxiv.org/rss/quant-ph"
    - title: "arXiv.org/stat"
      url: "https://rss.arxiv.org/rss/stat"

  journals:
    - title: "ACS Synthetic Biology"
      url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=asbcd6"
    - title: "Annual Reviews: Analytical Chemistry"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=6690&jc=anchem&type=etoc&feed=atom"
      stale_days: 365
    - title: "Annual Reviews: Astronomy and Astrophysics"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=6690&jc=astro&type=etoc&feed=atom"
      stale_days: 365
    - title: "Annual Reviews: Biochemistry"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=se&jc=biochem&type=etoc&feed=atom"
      stale_days: 365
    - title: "Annual Reviews: Biophysics"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=s7&jc=biophys&type=etoc&feed=atom"
      stale_days: 365
    - title: "Annual Reviews: Condensed Matter Physics"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=68t8&jc=conmatphys&type=etoc&feed=atom"
      stale_days: 365
    - title: "Annual Reviews: Earth and Planetary Sciences"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=s0&jc=earth&type=etoc&feed=atom"
      stale_days: 365
    - title: "Annual Reviews: Ecology, Evolution, and Systematics"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=sh&jc=ecolsys&type=etoc&feed=atom"
      stale_days: 365
    - title: "Annual Reviews: Genetics"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=sj&jc=genet&type=etoc&feed=atom"
      stale_days: 365
    - title: "Annual Reviews: Microbiology"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=sn&jc=micro&type=etoc&feed=atom"
      stale_days: 365
    - title: "Annual Reviews: Physical Chemistry"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=sy&jc=physchem&type=etoc&feed=atom"
      stale_days: 365
    - title: "Annual Reviews: Virology"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=6690&jc=virology&type=etoc&feed=atom"
      stale_days: 365
    - title: "BioEssays"
      url: "https://onlinelibrary.wiley.com/rss/journal/10.1002/(ISSN)1521-1878"
    - title: "Biosystems"
      url: "https://rss.sciencedirect.com/publication/science/03032647"
    - title: "Chaos"
      url: "https://pubs.aip.org/rss/site_1000025/1000015.xml"
    - title: "PLOS Complex Systems"
      url: "https://journals.plos.org/complexsystems/feed/atom"
    - title: "eLife"
      url: "https://elifesciences.org/rss/recent.xml"
    - title: "J Syst Sci Complex"
      url: "https://link.springer.com/search.rss?facet-content-type=Article&facet-journal-id=11424"
    - title: "Journal of Computational Science"
      url: "https://rss.sciencedirect.com/publication/science/18777503"
    - title: "Journal of Evolutionary Biology"
      url: "https://academic.oup.com/rss/site_6606/4185.xml"
      stale_days: 90
    - title: "Journal of Evolutionary Biology (Advance Access)"
      url: "https://academic.oup.com/rss/site_6606/advanceAccess_4185.xml"
    - title: "Journal of The Royal Society Interface"
      url: "https://royalsocietypublishing.org/rss/site_1000019/1000012.xml"
    - title: "Journal of Theoretical Biology"
      url: "https://rss.sciencedirect.com/publication/science/00225193"
    - title: "Nature"
      url: "https://www.nature.com/nature.rss"
    - title: "Nature Biotechnology"
      url: "https://www.nature.com/nbt.rss"
    - title: "Nature Cell Biology"
      url: "https://www.nature.com/ncb.rss"
    - title: "Nature Chemistry"
      url: "https://www.nature.com/nchem.rss"
    - title: "Nature Communications"
      url: "https://feeds.nature.com/ncomms/rss/current"
    - title: "Nature Ecology & Evolution"
      url: "https://www.nature.com/natecolevol.rss"
    - title: "Nature Genetics"
      url: "https://www.nature.com/ng.rss"
    - title: "Nature Medicine"
      url: "https://www.nature.com/nm.rss"
    - title: "Nature Methods"
      url: "https://www.nature.com/nmeth.rss"
    - title: "Nature Neuroscience"
      url: "https://www.nature.com/neuro.rss"
    - title: "Nature Physics"
      url: "https://www.nature.com/nphys.rss"
    - title: "Nature Structural & Molecular Biology"
      url: "https://www.nature.com/nsmb.rss"
    - title: "nature.com - Astronomy and Planetary Science"
      url: "https://www.nature.com/subjects/astronomy-and-planetary-science.rss"
    - title: "nature.com - Biochemistry"
      url: "https://www.nature.com/subjects/biochemistry.rss"
    - title: "nature.com - Biogeochemistry"
      url: "https://www.nature.com/subjects/biogeochemistry.rss"
    - title: "nature.com - Biophysics"
      url: "https://www.nature.com/subjects/biophysics.rss"
    - title: "nature.com - Biotechnology"
      url: "https://www.nature.com/subjects/biotechnology.rss"
    - title: "nature.com - Cell Biology"
      url: "https://www.nature.com/subjects/cell-biology.rss"
    - title: "nature.com - Chemical Biology"
      url: "https://www.nature.com/subjects/chemical-biology.rss"
    - title: "nature.com - Chemistry"
      url: "https://www.nature.com/subjects/chemistry.rss"
    - title: "nature.com - Complex Networks"
      url: "https://www.nature.com/subjects/complex-networks.rss"
    - title: "nature.com - Computational Biology and Bioinformatics"
      url: "https://www.nature.com/subjects/computational-biology-and-bioinformatics.rss"
    - title: "nature.com - Developmental Biology"
      url: "https://www.nature.com/subjects/developmental-biology.rss"
    - title: "nature.com - Ecology"
      url: "https://www.nature.com/subjects/ecology.rss"
    - title: "nature.com - Evolution"
      url: "https://www.nature.com/subjects/evolution.rss"
    - title: "nature.com - Genetics"
      url: "https://www.nature.com/subjects/genetics.rss"
    - title: "nature.com - Mathematics and Computing"
      url: "https://www.nature.com/subjects/mathematics-and-computing.rss"
    - title: "nature.com - Microbiology"
      url: "https://www.nature.com/subjects/microbiology.rss"
    - title: "nature.com - Molecular Biology"
      url: "https://www.nature.com/subjects/molecular-biology.rss"
    - title: "nature.com - Neuroscience"
      url: "https://www.nature.com/subjects/neuroscience.rss"
    - title: "nature.com - Ocean Sciences"
      url: "https://www.nature.com/subjects/ocean-sciences.rss"
    - title: "nature.com - Physics"
      url: "https://www.nature.com/subjects/physics.rss"
    - title: "nature.com - Planetary Science"
      url: "https://www.nature.com/subjects/planetary-science.rss"
    - title: "nature.com - Space Physics"
      url: "https://www.nature.com/subjects/space-physics.rss"
    - title: "nature.com - Structural Biology"
      url: "https://www.nature.com/subjects/structural-biology.rss"
    - title: "nature.com - Systems Biology"
      url: "https://www.nature.com/subjects/systems-biology.rss"
    - title: "Icarus"
      url: "https://rss.sciencedirect.com/publication/science/00191035"
    - title: "npj Complexity"
      url: "https://www.nature.com/npjcomplex/rss"
    - title: "The Planetary Science Journal"
      url: "https://iopscience.iop.org/journal/rss/2632-3338"
    - title: "Philosophical Transactions A"
      url: "https://royalsocietypublishing.org/rss/site_1000005/1000005.xml"
    - title: "Philosophical Transactions B"
      url: "https://royalsocietypublishing.org/rss/site_1000007/1000006.xml"
    - title: "Phys. Rev. E"
      url: "https://feeds.aps.org/rss/recent/pre.xml"
    - title: "Phys. Rev. Lett."
      url: "https://feeds.aps.org/rss/recent/prl.xml"
    - title: "Physics of Life Reviews"
      url: "https://rss.sciencedirect.com/publication/science/15710645"
    - title: "PLOS Biology"
      url: "https://journals.plos.org/plosbiology/feed/atom"
    - title: "PLOS Computational Biology"
      url: "https://www.ploscompbiol.org/article/feed"
    - title: "PNAS"
      url: "https://www.pnas.org/rss/ahead.xml"
    - title: "Protein Science"
      url: "https://onlinelibrary.wiley.com/rss/journal/10.1002/(ISSN)1469-896X"
    - title: "Science"
      url: "https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=science"
    - title: "Science Advances"
      url: "https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=sciadv"
    - title: "Science Immunology"
      url: "https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=sciimmunol"
    - title: "Science Robotics"
      url: "https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=scirobotics"
    - title: "Science Signaling"
      url: "https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=signaling"
    - title: "Science Translational Medicine"
      url: "https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=stm"
    - title: "Scientific Reports"
      url: "https://feeds.nature.com/srep/rss/current"

  journals_pubmed:
    - title: "alife (MIT Press)"
      url: "https://pubmed.ncbi.nlm.nih.gov/rss/journals/9433814/?limit=100&name=Artif%20Life&utm_campaign=journals"
    - title: "Evol Comput"
      url: "https://pubmed.ncbi.nlm.nih.gov/rss/journals/9513581/?limit=100&name=Evol%20Comput&utm_campaign=journals"
    - title: "Life (MDPI)"
      url: "https://pubmed.ncbi.nlm.nih.gov/rss/journals/101580444/?limit=100&name=Life%20%28Basel%29&utm_campaign=journals"
    - title: "Entropy (MDPI)"
      url: "https://pubmed.ncbi.nlm.nih.gov/rss/journals/101243874/?limit=100&name=Entropy%20%28Basel%29&utm_campaign=journals"
    - title: "Astrobiology (Mary Ann Liebert)"
      url: "https://pubmed.ncbi.nlm.nih.gov/rss/journals/101088083/?limit=100&name=Astrobiology&utm_campaign=journals"